/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#include <stdint.h>
#include <stdio.h>


int main(void)
{
	//1. Enable all configurable exceptions like usage fault, mem manage fault, bus fault
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |= (1 << 18);
	*pSHCSR |= (1 << 17);
	*pSHCSR |= (1 << 16);


	//3. lets force the processor to execute some undefined instruction
	uint32_t *pSRAM = (uint32_t*)0x20010000;
	*pSRAM = 0xFFFFFFFF;

	void (*some_address) (void);

	some_address = (void*)(((uint32_t)pSRAM)+1);

	some_address();
	//4. analyze the fault
}

//2. implement the fault handler
void HardFault_Handler(void)
{
	printf("Exception: HardFault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exception: MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception: BusFault\n");
	while(1);
}

__attribute__((naked)) void UsageFault_Handler(void)
{
	__asm ("MRS r0, MSP");
	__asm ("B UsageFault_Handler_c");
}

void UsageFault_Handler_c(uint32_t *pMSP)
{
	printf("MSP = %p\n", pMSP);
	printf("Value of R0   = 0x%lx\n",pMSP[0]);
	printf("Value of R1   = 0x%lx\n",pMSP[1]);
	printf("Value of R2   = 0x%lx\n",pMSP[2]);
	printf("Value of R3   = 0x%lx\n",pMSP[3]);
	printf("Value of R12  = 0x%lx\n",pMSP[4]);
	printf("Value of LR   = 0x%lx\n",pMSP[5]);
	printf("Value of PC   = 0x%lx\n",pMSP[6]);
	printf("Value of XPSR = 0x%lx\n",pMSP[7]);


	printf("Exception: UsageFault\n");
	uint32_t *pUFSR = (uint32_t*) 0xE000ED2A;
	switch ((*pUFSR) & 0xFFFF){
	case 0x0001:
		printf("the processor has attempted to execute an undefined instruction.\n");
		break;
	case 0x0002:
		printf("the processor has attempted to execute an instruction that makes illegal use of the EPSR.\n");
		break;
	default:
		break;
	}

	while(1);
}

