/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#include <stdint.h>
#include <stdio.h>


void SVC_executioner(int n)
{
	__asm__ volatile("SVC %0"::"r"(n));

}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame);

int main(void)
{

	SVC_executioner(5);

	for(;;);
}

__attribute__ ((naked)) void SVC_Handler(void)
{
	//Extract SVC Number
	//1. Get MSP value
	__asm("MRS R0, MSP");
	__asm("B SVC_Handler_c");//R0 will be copy to argument 0
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame)
{
	printf("in SVC Handler\n");
	printf("Base address of Stack Frame = %p\n", pBaseOfStackFrame);

	//2. Subtract MSP value by 6 to get PC(return address) value
	uint8_t *pReturn_addr = (uint8_t*)pBaseOfStackFrame[6];
	printf("Address of Return = %p\n", pReturn_addr);

	//3. Minus PC value by 2 to get SVC number because SVC number is right before return address when SVC Handler is done

	uint8_t *svc_number = (uint8_t*)(pReturn_addr - 2);
	printf("SVC number is: %d\n", *svc_number);

}


