/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"


void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

void enable_processor_faults(void);

__attribute__ ((naked)) void init_scheduler_stack(uint32_t top_of_stack);

void init_tasks_stack(void);

void init_systick_timer(uint32_t tick_hz);

__attribute__((naked))void switch_msp_to_psp(void);

void tasks_delay(uint32_t ticks_count);

uint8_t current_task = 1;//task1 is running
uint32_t g_tick_count = 0;

uint32_t get_psp_value(void);

void update_next_task(void);
void save_psp_value(uint32_t current_psp_value);

typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];
//semihosting init func
extern void initialise_monitor_handles(void);

int main(void)
{
	enable_processor_faults();
	
	initialise_monitor_handles();

	init_scheduler_stack(SCHEDULER_STACK_START);
	
	printf("Implementation of simple tasks scheduler\n");

	init_tasks_stack();

    init_systick_timer(TICK_HZ);

    switch_msp_to_psp();

    led_init();
    task1_handler();

	for(;;);
}
void idle_task(void)
{
	while(1);
}

void task1_handler(void)
{
	while(1)
	{
		printf("Task1 is executing\n");
		led_on(10);
		tasks_delay(1000);
		led_off(10);
		tasks_delay(1000);
	}
}

void task2_handler(void)
{
	while(1)
	{
		printf("Task2 is executing\n");
		led_on(9);
		tasks_delay(500);
		led_off(9);
		tasks_delay(500);
	}
}

void task3_handler(void)
{
	while(1)
	{
		printf("Task3 is executing\n");
		led_on(8);
		tasks_delay(250);
		led_off(8);
		tasks_delay(250);
	}
}

void task4_handler(void)
{
	while(1)
	{
		printf("Task4 is executing\n");
		led_on(5);
		tasks_delay(125);
		led_off(5);
		tasks_delay(125);
	}
}
void enable_processor_faults(void)
{
	//1. Enable all configurable exceptions like usage fault, mem manage fault, bus fault
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |= (1 << 18);
	*pSHCSR |= (1 << 17);
	*pSHCSR |= (1 << 16);
}
void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSRVR = (uint32_t*)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;
	uint32_t count_value = ( (SYSTICK_TIM_CLK / tick_hz) - 1);

	//Clear the value of SVR
	*pSRVR &= ~(0x00FFFFFF);

	//load the value in to SVR
	*pSRVR |= count_value;

	//do some settings
	*pSCSR |= ( 1 << 1 ); //Enables SysTick exception
	*pSCSR |= ( 1 << 2 ); //Indicates the clock source, processor clock source

	//enable systick timer
	*pSCSR |= ( 1 << 0 ); //Enable the counter
}

__attribute__ ((naked))void init_scheduler_stack(uint32_t top_of_stack)
{
	__asm volatile("MSR MSP, %0": : "r"(top_of_stack) : );
	__asm volatile("BX LR");
}

void init_tasks_stack(void)
{
	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP;

	for(int i = 0; i < MAX_TASKS; i++)
	{
		pPSP = (uint32_t*)user_tasks[i].psp_value;

		pPSP--;//XPSR
		*pPSP = DUMMY_XPSR; //0x0100000

		pPSP--;//PC
		*pPSP = (uint32_t)user_tasks[i].task_handler;

		pPSP--;//LR
		*pPSP = 0xFFFFFFFDU;

		for(int j = 0; j < 13; j++)
		{
			pPSP--;
			*pPSP = 0;
		}

		user_tasks[i ].psp_value = (uint32_t)pPSP;
	}
}



__attribute__((naked))void switch_msp_to_psp(void)
{
	//1. initialize the PSP with TASK1 stack start

	//get the value of psp of current_task
	__asm volatile ("PUSH {LR}"); //preserve LR
	__asm volatile ("BL get_psp_value");
	__asm volatile ("MSR PSP, R0");//initialize PSP
	__asm volatile ("POP {LR}");
	//2. change SP to PSP using CONTROL register
	__asm volatile ("MOV R0, #0x02");
	__asm volatile ("MSR CONTROL, R0");
	__asm volatile ("BX LR");
}
void schedule(void)
{
	uint32_t *pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= ( 1 << 28 );
}

void tasks_delay(uint32_t ticks_count)
{
	INTERRUPT_DISABLE();
	if(current_task != 0)
	{
		user_tasks[current_task].block_count = ( g_tick_count + ticks_count);
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();
	}
	INTERRUPT_ENABLE();
}



void save_psp_value(uint32_t current_psp_value)
{
	user_tasks[current_task].psp_value = current_psp_value;
}

void update_next_task(void)
{
	int state = TASK_BLOCKED_STATE;
	for(int i = 0; i < MAX_TASKS; i++)
	{
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if((state == TASK_READY_STATE) && (current_task != 0))
			break;
	}
	if(state != TASK_READY_STATE)
		current_task = 0;
}

uint32_t get_psp_value(void)
{

	return user_tasks[current_task].psp_value;
}
void update_g_tick_count(void)
{
	g_tick_count++;
}

void unblock_tasks(void)
{
	for(int i = 1; i < MAX_TASKS; i++)
	{
		if(user_tasks[i].current_state != TASK_READY_STATE)
		{
			if(user_tasks[i].block_count == g_tick_count)
			{
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}

	}
}

void SysTick_Handler(void)
{
	update_g_tick_count();
	unblock_tasks();
	//pend the pendSV exception
	uint32_t *pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= ( 1 << 28 );
}

__attribute__((naked))void PendSV_Handler(void)
{
	/* Save the context of current task */
	//1. Get current running task's PSP value
	__asm volatile("MRS R0, PSP");
	//2. Using that PSP value store SF2 (R4 - R11)
	__asm volatile("STMDB R0!, {R4-R11}");
	//3. Save the current value of PSP
	__asm volatile("PUSH {LR}");
	__asm volatile("BL save_psp_value");


	/* Retrivev the context of next task */
	//1. Decide next task to run
	__asm volatile("BL update_next_task");
	//2. get its past PSP value
	__asm volatile ("BL get_psp_value");
	//3. Using that PSP value retrieve SF2 (R4 - R11)
	__asm volatile("LDMIA R0!, {R4-R11}");
	//4. Update PSP and exit
 	__asm volatile("MSR PSP, R0");
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");
}

void HardFault_Handler(void)
{
	printf("Exception: HardFault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exception: MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception: BusFault\n");
	while(1);
}
