/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#include <stdint.h>
#include <stdio.h>

#define USART2_IRQNO 38

int main(void)
{
	//1. Manually pend the pending bit for the USART2 IRQ number in NVIC
	uint32_t *pISPR1 = (uint32_t*)0XE000E204;
	*pISPR1 |= (1 << (USART2_IRQNO % 32));

	//2. Enable the USART2 IRQ number in NVIC
	uint32_t *pISER1 = (uint32_t*)0XE000E104;
	*pISER1 |= (1 << (USART2_IRQNO % 32));


	for(;;);
}

//USART2 ISR
void USART2_IRQHandler(void)
{
	printf("in USART2 ISR\n");
}
