/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#include <stdint.h>
#include <stdio.h>




void SVC_Handler_c(uint32_t *pBaseOfStackFrame);

int32_t SVC_Add_func(int32_t x, int32_t y)
{
	int32_t res;
	__asm volatile("SVC #36");
	__asm volatile("MOV %0, R0":"=r"(res)::);
	return res;
}

int32_t SVC_Sub_func(int32_t x, int32_t y)
{
	int32_t res;
	__asm volatile("SVC #37");
	__asm volatile("MOV %0, R0":"=r"(res)::);
	return res;
}
int32_t SVC_Mul_func(int32_t x, int32_t y)
{
	int32_t res;
	__asm volatile("SVC #38");
	__asm volatile("MOV %0, R0":"=r"(res)::);
	return res;
}
int32_t SVC_Div_func(int32_t x, int32_t y)
{
	int32_t res;
	__asm volatile("SVC #39");
	__asm volatile("MOV %0, R0":"=r"(res)::);
	return res;
}

int main(void)
{
	int32_t res;

	res = SVC_Add_func(10, -90);
	printf("add res = %ld\n", res);
	res = SVC_Sub_func(10, 20);
	printf("sub res = %ld\n", res);
	res = SVC_Mul_func(10, 20);
	printf("mul res = %ld\n", res);
	res = SVC_Div_func(100, -20);
	printf("div res = %ld\n", res);
	for(;;);
}

__attribute__ ((naked)) void SVC_Handler(void)
{
	//Extract SVC Number
	//1. Get MSP value
	__asm("MRS R0, MSP");
	__asm("B SVC_Handler_c");//R0 will be copy to argument 0
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame)
{
	//2. Subtract MSP value by 6 to get PC(return address) value
	uint8_t *pReturn_addr = (uint8_t*)pBaseOfStackFrame[6];

	int32_t x,y,result;
	x = pBaseOfStackFrame[0];
	y = pBaseOfStackFrame[1];
	//3. Minus PC value by 2 to get SVC number because SVC number is right before return address when SVC Handler is done

	uint32_t *pSVC_number = (uint32_t*)(pReturn_addr - 2);
	uint8_t SVC_number =(uint8_t)((*pSVC_number) & 0xFF);
	switch (SVC_number)
	{
		case 36:
			result = x + y;
			break;
		case 37:
			result = x - y;
			break;
		case 38:
			result = x * y;
			break;
		case 39:
			result = x / y;
			break;
		default:
			printf("Invalid SVC number: %d?\n",SVC_number);
			break;
	}
		pBaseOfStackFrame[0] = result;
}


