/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#include <stdint.h>
#include <stdio.h>




uint32_t *pNVIC_ISER0 = (uint32_t*)0XE000E100;

uint32_t *pSTIR = (uint32_t*)0xE000EF00;

void generate_interrupt(void)
{
	*pNVIC_ISER0 |= ( 1 << 3);

	*pSTIR = (3 & 0x1FF);
}

int main(void)
{
	printf("In thread mode: before interrupt\n");

	generate_interrupt();

	printf("In thread mode: after interrupt\n");

	for(;;);
}

//ISRs
void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode: ISR\n");

}


